// The reading-room side computer: a tired hospital desktop with apps (RiskMann, Bidly) and whatever files the
// last eleven registrars left on it. Everything here is fictional.
import { openRiskman } from './riskman.js';
import { openStore } from './store.js';

const $ = (id) => document.getElementById(id);
const esc = (s) => String(s).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c]);

// Text documents. The AI-assisted ones still have the chatbot's reply pasted at the bottom, because nobody proofread.
const FILES = {
  casereport: {
    name: 'appendix case report DRAFT v4 - Copy.docx', icon: 'doc', kind: 'doc',
    body: `# Retrocaecal appendicitis mimicking renal colic [title?? something better]

Authors: me, Dr ____ (ask if he wants to be first author AGAIN), ?the surgical reg (did nothing)

## Abstract
[write this last]

## Background
Appendicitis is the most common general surgical emergency, lifetime risk approx XX% [ref]. Retrocaecal is the commonest position (65%?? check) but can present atypically — flank pain, few peritoneal signs, sometimes microscopic haematuria [ref]. Often mistaken for renal colic.

[RH comment: too long, cut to 2 lines]

## Case presentation
34M, previously well, presented at 02:40 with ~18 h of R flank pain radiating to the groin. Nausea, vomited once. T 37.6. Mild R loin tenderness, no guarding. Urine dip: trace blood. WCC 13.1, CRP 42 (or 48? check the second set).

Treated as renal colic → CT KUB "?stone ?obstruction".

CT KUB: no calculus, no hydronephrosis. Dilated XX mm tubular structure arising from the caecum and extending superiorly behind it, with surrounding fat stranding and a XX mm appendicolith at the base. No free gas or collection.

[Fig 1 — axial CT, arrow on appendicolith. DE-IDENTIFY FIRST]
[Fig 2 — coronal?? if it looks ok]

Surgeons informed 03:55 (they said "clinically renal colic" — leave this out?). Lap appendicectomy the same morning: gangrenous retrocaecal appendix. Histo: acute suppurative appendicitis. Home day 2.

## Discussion
The retrocaecal appendix lies behind the caecum and can sit against the right ureter, which explains the flank pain and the haematuria. Because the caecum shields it, the anterior peritoneal signs are often absent [ref].

Non-contrast CT is less sensitive than contrast-enhanced CT for appendicitis, however an appendicolith and fat stranding are usually

OLD VERSION — delete?: Non contrast CT is less sensitive but the appendicolith is often the most obvious finding and radiologists should always look for

Something about the importance of a search pattern on "negative" CT KUBs — diverticulitis, adnexal, AAA, appendix

## Learning points
- Retrocaecal appendicitis can mimic R renal colic (incl. haematuria)
- Negative CT KUB → look for another cause
- 3rd point???

## References
1. [ref]
2. [ref — retrocaecal presentation]
3. [the RANZCR one? or was it RCR]

## Patient consent
[CHECK — did anyone actually get this??]

Word count: ~650 (limit 1500, so fine)

I've tidied up the sections you pasted and made them sound more natural and less like they were generated by AI. Here's a summary of the changes I made:

- **Varied sentence length and structure** so it reads more like a clinician wrote it
- **Removed overused phrases** such as "delve", "tapestry" and "in today's fast-paced clinical landscape"
- **Kept your notes and placeholders** (XX, [ref]) so you can fill them in from the patient's records
- **Left the references as placeholders**, as I wasn't able to verify that the original citations exist. Please check these against PubMed before submission.

Please note that most journals now require authors to disclose the use of AI tools in manuscript preparation, so you may wish to add a statement to the acknowledgements.

Would you like me to:
1. Write the abstract?
2. Suggest a few catchier titles?
3. Draft a third learning point?

Let me know if there's anything else I can help with!`,
  },
  rota: {
    name: 'Rota_FINAL_v7_ACTUALFINAL(2).xlsx', icon: 'xls', kind: 'sheet',
    rows: [
      ['', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      ['Day', 'Lim', 'Okafor', 'Lim', 'LEAVE', 'Okafor', '—', '—'],
      ['Evening', 'Patel', 'Patel', 'Novak', 'Novak', 'Patel', 'Lim', 'Novak'],
      ['NIGHT', 'YOU', 'YOU', 'YOU', 'YOU', 'YOU', 'YOU', 'YOU'],
      ['Backup', 'YOU', 'YOU', '#REF!', '#REF!', 'YOU', 'YOU', 'YOU'],
      ['Leave req.', 'YOU (declined)', '', '', '', '', '', 'Okafor (approved, Bali)'],
    ],
  },
  passwords: {
    name: 'passwords.txt', icon: 'txt', kind: 'pre',
    body: `PACS: Password1
PACS (after forced reset): Password2
PACS (after forced reset again): Password3!
RiskMann: same as PACS but with "Risk" in front
Rota system: ask Linda
Linda's password: ask Linda
Wi-Fi: Guest-NoAccess
Car park gate code: 1234 (it was 0000 but security said that was "too obvious")
Coffee machine admin: there is no admin. It is in control now.
DO NOT LEAVE THIS FILE ON THE DESKTOP — IT`,
  },
  resignation: {
    name: 'resignation_letter_DO_NOT_SEND.docx', icon: 'doc', kind: 'doc',
    body: `Dear Director of Medical Services,

Please accept this letter as formal notice of my resignation from the position of on-call radiologist, effective immediately / at 08:00 / when I find my car.

After 14 years, 31,000 CT brains and one memorable night involving a microwave, I have decided to pursue other opportunities, such as sleeping.

I would like to thank the surgical registrars for teaching me that every scan is urgent, and the ED for teaching me that "?anything" is a clinical question.

Yours sincerely,
(the radiologist)

I've drafted a resignation letter based on your notes. A few suggestions before you send it:

- You may want to keep the tone more positive, as it's generally wise to maintain good professional relationships with a former employer.
- "Effective immediately / at 08:00 / when I find my car" should be a single date. Most contracts require a notice period of four to twelve weeks.

Would you like me to write a more formal version?`,
  },
  teaching: {
    name: 'Registrar_teaching_FINAL.pptx', icon: 'ppt', kind: 'doc',
    body: `# Slide 1: How to request a CT

# Slide 2: Don't.

# Slide 3: (Just kidding.) Include:
- A clinical question
- The patient's renal function
- The correct patient

# Slide 4: Real request forms (anonymised)
- "?anything"
- "pain"
- "please scan, family very anxious, consultant very anxious, I am very anxious"
- "CT whole body ?why unwell"

# Slide 5: Questions?

# Slide 6: (picture of a cat holding a stethoscope)`,
  },
  cat: { name: 'IMG_4471_cat_in_scanner.jpg', icon: 'img', kind: 'cat' },
  readme: {
    name: 'README_IT.txt', icon: 'txt', kind: 'pre',
    body: `This computer is scheduled for a Windows update.
It has been scheduled since 2017.
Do not turn off.
Do not turn on.
Do not install games.
If you can read this, IT would like their stapler back.`,
  },
};

const ICONS = [
  { id: 'riskman', name: 'RiskMann', icon: 'app-rm' },
  { id: 'store', name: 'Bidly', icon: 'app-bid' },
  { id: 'casereport' }, { id: 'rota' }, { id: 'teaching' }, { id: 'resignation' },
  { id: 'passwords' }, { id: 'cat' }, { id: 'readme' },
  { id: 'bin', name: 'Recycle Bin', icon: 'bin' },
];

const GLYPH = { doc: 'W', xls: 'X', ppt: 'P', txt: '≡', img: '▣', bin: '🗑', 'app-rm': 'R', 'app-bid': 'b' };

export function openDesktop(G, { onClose }) {
  const d = $('desktop');
  const el = $('dt-icons');
  el.innerHTML = ICONS.map((ic) => {
    const f = FILES[ic.id];
    const name = ic.name || f.name, icon = ic.icon || f.icon;
    return `<button class="dt-icon" data-open="${ic.id}"><span class="dt-glyph dt-${icon}">${GLYPH[icon]}</span><span class="dt-name">${esc(name)}</span></button>`;
  }).join('');
  const armed = () => performance.now() - (+d.dataset.openedAt || 0) > 450;
  for (const b of el.querySelectorAll('[data-open]')) b.onclick = () => { if (armed()) launch(G, b.dataset.open); };
  $('dt-shutdown').onclick = () => { if (!armed()) return; closeAll(); onClose(); };
  $('dt-start').onclick = () => { if (armed()) toast('Start menu has been disabled by your administrator.'); };
  $('fv-close').onclick = () => { $('fileview').hidden = true; };
  $('dt-clock').textContent = $('clock').textContent;
  d.hidden = false;
  d.dataset.openedAt = performance.now();

  function toast(msg) { const n = $('dt-note'); n.textContent = msg; n.hidden = false; clearTimeout(n._t); n._t = setTimeout(() => { n.hidden = true; }, 2600); }
  function closeAll() { d.hidden = true; $('fileview').hidden = true; $('riskman').hidden = true; $('store').hidden = true; }
  function launch(G, id) {
    if (id === 'riskman') { openRiskman(G, { onClose: () => {} }); return; }
    if (id === 'store') { openStore(G, { onClose: () => {} }); return; }
    if (id === 'bin') { showFile({ name: 'Recycle Bin', kind: 'pre', body: 'audit_data_REAL.xlsx\nmy_dignity.tmp\nCPD_portfolio_2019-2024 (never started).docx\nLetter_of_complaint_draft_47.docx' }); return; }
    if (FILES[id]) showFile(FILES[id]);
  }
}

function showFile(f) {
  $('fv-title').textContent = f.name;
  const body = $('fv-body');
  body.className = 'fv-body fv-' + f.kind;
  if (f.kind === 'sheet') {
    body.innerHTML = `<table>${f.rows.map((r, i) => `<tr>${r.map((c) => i === 0 ? `<th>${esc(c)}</th>` : `<td class="${c === 'YOU' ? 'fv-you' : c === '#REF!' ? 'fv-err' : ''}">${esc(c)}</td>`).join('')}</tr>`).join('')}</table>`;
  } else if (f.kind === 'cat') {
    body.innerHTML = `<div class="fv-cat"><div class="fv-catimg">=^..^=</div><p>The ward cat, mid-CT. The DLP was unremarkable. The cat was not.</p></div>`;
  } else if (f.kind === 'pre') {
    body.innerHTML = `<pre>${esc(f.body)}</pre>`;
  } else {
    body.innerHTML = docHtml(f.body);
  }
  $('fileview').hidden = false;
  body.scrollTop = 0;
}

// Tiny markdown-ish renderer: headings, bold, bullets, numbered items, and highlighted author TODOs.
function docHtml(src) {
  const inline = (s) => esc(s)
    .replace(/\*\*(.+?)\*\*/g, '<b>$1</b>')
    .replace(/(\[[^\]]+\]|\bXX\b|\?\?\?)/g, '<span class="fv-todo">$1</span>');
  const out = [];
  let list = false;
  for (const line of src.split('\n')) {
    if (/^- /.test(line)) { if (!list) { out.push('<ul>'); list = true; } out.push(`<li>${inline(line.slice(2)) || '&nbsp;'}</li>`); continue; }
    if (list) { out.push('</ul>'); list = false; }
    if (/^# /.test(line)) out.push(`<h1>${inline(line.slice(2))}</h1>`);
    else if (/^## /.test(line)) out.push(`<h2>${inline(line.slice(3))}</h2>`);
    else if (line.trim()) out.push(`<p>${inline(line)}</p>`);
  }
  if (list) out.push('</ul>');
  return out.join('');
}
