// The reading-room side computer: a tired hospital desktop with apps (RiskMann, Bidly) and whatever files the
// last eleven registrars left on it. Everything here is fictional.
import { openRiskman } from './riskman.js';
import { openStore } from './store.js';

const $ = (id) => document.getElementById(id);
const esc = (s) => String(s).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c]);

// Text documents. The AI-assisted ones still have the chatbot's reply pasted at the bottom, because nobody proofread.
const FILES = {
  casereport: {
    name: 'Case_report_FINAL_for_submission.docx', icon: 'doc', kind: 'doc',
    body: `# Retrocaecal appendicitis mimicking right renal colic: a case report

Authors: Dr ____ (Radiology Registrar), Dr ____ (Consultant Radiologist — check if he wants to be first author again)

## Abstract
We report the case of a 34-year-old man who presented to the Emergency Department with right flank pain initially attributed to renal colic. A non-contrast CT KUB showed no urolithiasis but did demonstrate an inflamed retrocaecal appendix with an appendicolith. He underwent laparoscopic appendicectomy and made an uneventful recovery. This case is a reminder that the appendix does not always sit where the clinical examination expects it to.

## Background
Acute appendicitis is the most common general surgical emergency, with a lifetime risk of around 7–8% [1]. The retrocaecal position is the most frequent anatomical variant, yet retrocaecal appendicitis can present atypically, with flank or back pain, few peritoneal signs and occasionally microscopic haematuria from ureteric irritation [2]. Unsurprisingly, it is often mistaken for renal colic.

## Case presentation
A previously well 34-year-old man presented at 02:40 with 18 hours of right flank pain radiating to the groin, with nausea and one episode of vomiting. He was afebrile (37.6°C) with mild right loin tenderness and no rebound or guarding. Urinalysis showed a trace of blood. WCC was 13.1 and CRP 42.

He was treated as renal colic and a CT KUB was requested ("?stone ?obstruction"). There was no urinary tract calculus and no hydronephrosis. In the right paracolic region there was a dilated 10 mm tubular structure arising from the caecum and extending superiorly behind it, with surrounding fat stranding and a 5 mm appendicolith at its base. There was no free gas or collection.

The surgical team were informed at 03:55. He underwent laparoscopic appendicectomy the same morning, which confirmed a gangrenous retrocaecal appendix. Histology showed acute suppurative appendicitis. He was discharged on day two.

## Discussion
The retrocaecal appendix lies behind the caecum and may be in contact with the right ureter and the posterior abdominal wall, which explains the flank pain and the haematuria in this patient. Because the inflamed appendix is shielded by the caecum, the classic signs of anterior peritoneal irritation are often absent [3].

Non-contrast CT is less sensitive for appendicitis than contrast-enhanced CT, but an appendicolith and periappendiceal stranding are usually visible. Radiologists reviewing a "negative" CT KUB should actively look for alternative diagnoses, including appendicitis, diverticulitis and adnexal pathology [4].

## Learning points
- Retrocaecal appendicitis can mimic right renal colic, including haematuria.
- A negative CT KUB should prompt a search for alternative causes of flank pain.
- An appendicolith may be the most conspicuous finding on non-contrast CT.

## References
1. [ref — lifetime risk of appendicitis, find a proper one]
2. [ref — retrocaecal presentation]
3. [ref]
4. [ref — alternative diagnoses on CT KUB, the RANZCR one?]

## Patient consent
Obtained [CHECK — did anyone actually get this??]

I've revised your case report to sound more natural and less like it was generated by AI. Here's a summary of the changes I made:

- **Varied sentence length and structure** so it reads more like a clinician wrote it
- **Removed overused phrases** such as "delve", "tapestry" and "in today's fast-paced clinical landscape"
- **Added specific clinical details** (times, observations, blood results) to make the case feel more authentic
- **Trimmed the word count** to approximately 780 words, well within the BMJ Case Reports limit
- **Replaced the references** with placeholders, as I wasn't able to verify that the original citations exist. Please check these against PubMed before submission.

Please note that most journals now require authors to disclose the use of AI tools in manuscript preparation, so you may wish to add a statement to the acknowledgements.

Would you like me to:
1. Suggest a few catchier titles?
2. Draft a cover letter to the editor?
3. Write the patient consent section?

Let me know if there's anything else I can help with!`,
  },
  rota: {
    name: 'Rota_FINAL_v7_ACTUALFINAL(2).xlsx', icon: 'xls', kind: 'sheet',
    rows: [
      ['', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      ['Day', 'Lim', 'Okafor', 'Lim', 'LEAVE', 'Okafor', '—', '—'],
      ['Evening', 'Patel', 'Patel', 'Novak', 'Novak', 'Patel', 'Lim', 'Novak'],
      ['NIGHT', 'YOU', 'YOU', 'YOU', 'YOU', 'YOU', 'YOU', 'YOU'],
      ['Backup', 'YOU', 'YOU', '#REF!', '#REF!', 'YOU', 'YOU', 'YOU'],
      ['Leave req.', 'YOU (declined)', '', '', '', '', '', 'Okafor (approved, Bali)'],
    ],
  },
  passwords: {
    name: 'passwords.txt', icon: 'txt', kind: 'pre',
    body: `PACS: Password1
PACS (after forced reset): Password2
PACS (after forced reset again): Password3!
RiskMann: same as PACS but with "Risk" in front
Rota system: ask Linda
Linda's password: ask Linda
Wi-Fi: Guest-NoAccess
Car park gate code: 1234 (it was 0000 but security said that was "too obvious")
Coffee machine admin: there is no admin. It is in control now.
DO NOT LEAVE THIS FILE ON THE DESKTOP — IT`,
  },
  resignation: {
    name: 'resignation_letter_DO_NOT_SEND.docx', icon: 'doc', kind: 'doc',
    body: `Dear Director of Medical Services,

Please accept this letter as formal notice of my resignation from the position of on-call radiologist, effective immediately / at 08:00 / when I find my car.

After 14 years, 31,000 CT brains and one memorable night involving a microwave, I have decided to pursue other opportunities, such as sleeping.

I would like to thank the surgical registrars for teaching me that every scan is urgent, and the ED for teaching me that "?anything" is a clinical question.

Yours sincerely,
(the radiologist)

P.S. The fish in the tea room was me.

I've drafted a resignation letter based on your notes. A few suggestions before you send it:

- You may want to keep the tone more positive, as it's generally wise to maintain good professional relationships with a former employer.
- "Effective immediately / at 08:00 / when I find my car" should be a single date. Most contracts require a notice period of four to twelve weeks.
- Consider removing the postscript.

Would you like me to write a more formal version?`,
  },
  teaching: {
    name: 'Registrar_teaching_FINAL.pptx', icon: 'ppt', kind: 'doc',
    body: `# Slide 1: How to request a CT

# Slide 2: Don't.

# Slide 3: (Just kidding.) Include:
- A clinical question
- The patient's renal function
- The correct patient

# Slide 4: Real request forms (anonymised)
- "?anything"
- "pain"
- "please scan, family very anxious, consultant very anxious, I am very anxious"
- "CT whole body ?why unwell"

# Slide 5: Questions?

# Slide 6: (picture of a cat holding a stethoscope)`,
  },
  cat: { name: 'IMG_4471_cat_in_scanner.jpg', icon: 'img', kind: 'cat' },
  readme: {
    name: 'README_IT.txt', icon: 'txt', kind: 'pre',
    body: `This computer is scheduled for a Windows update.
It has been scheduled since 2017.
Do not turn off.
Do not turn on.
Do not install games.
If you can read this, IT would like their stapler back.`,
  },
};

const ICONS = [
  { id: 'riskman', name: 'RiskMann', icon: 'app-rm' },
  { id: 'store', name: 'Bidly', icon: 'app-bid' },
  { id: 'casereport' }, { id: 'rota' }, { id: 'teaching' }, { id: 'resignation' },
  { id: 'passwords' }, { id: 'cat' }, { id: 'readme' },
  { id: 'bin', name: 'Recycle Bin', icon: 'bin' },
];

const GLYPH = { doc: 'W', xls: 'X', ppt: 'P', txt: '≡', img: '▣', bin: '🗑', 'app-rm': 'R', 'app-bid': 'b' };

export function openDesktop(G, { onClose }) {
  const d = $('desktop');
  const el = $('dt-icons');
  el.innerHTML = ICONS.map((ic) => {
    const f = FILES[ic.id];
    const name = ic.name || f.name, icon = ic.icon || f.icon;
    return `<button class="dt-icon" data-open="${ic.id}"><span class="dt-glyph dt-${icon}">${GLYPH[icon]}</span><span class="dt-name">${esc(name)}</span></button>`;
  }).join('');
  const armed = () => performance.now() - (+d.dataset.openedAt || 0) > 450;
  for (const b of el.querySelectorAll('[data-open]')) b.onclick = () => { if (armed()) launch(G, b.dataset.open); };
  $('dt-shutdown').onclick = () => { if (!armed()) return; closeAll(); onClose(); };
  $('dt-start').onclick = () => { if (armed()) toast('Start menu has been disabled by your administrator.'); };
  $('fv-close').onclick = () => { $('fileview').hidden = true; };
  $('dt-clock').textContent = $('clock').textContent;
  d.hidden = false;
  d.dataset.openedAt = performance.now();

  function toast(msg) { const n = $('dt-note'); n.textContent = msg; n.hidden = false; clearTimeout(n._t); n._t = setTimeout(() => { n.hidden = true; }, 2600); }
  function closeAll() { d.hidden = true; $('fileview').hidden = true; $('riskman').hidden = true; $('store').hidden = true; }
  function launch(G, id) {
    if (id === 'riskman') { openRiskman(G, { onClose: () => {} }); return; }
    if (id === 'store') { openStore(G, { onClose: () => {} }); return; }
    if (id === 'bin') { showFile({ name: 'Recycle Bin', kind: 'pre', body: 'audit_data_REAL.xlsx\nmy_dignity.tmp\nCPD_portfolio_2019-2024 (never started).docx\nLetter_of_complaint_draft_47.docx' }); return; }
    if (FILES[id]) showFile(FILES[id]);
  }
}

function showFile(f) {
  $('fv-title').textContent = f.name;
  const body = $('fv-body');
  body.className = 'fv-body fv-' + f.kind;
  if (f.kind === 'sheet') {
    body.innerHTML = `<table>${f.rows.map((r, i) => `<tr>${r.map((c) => i === 0 ? `<th>${esc(c)}</th>` : `<td class="${c === 'YOU' ? 'fv-you' : c === '#REF!' ? 'fv-err' : ''}">${esc(c)}</td>`).join('')}</tr>`).join('')}</table>`;
  } else if (f.kind === 'cat') {
    body.innerHTML = `<div class="fv-cat"><div class="fv-catimg">=^..^=</div><p>The ward cat, mid-CT. The DLP was unremarkable. The cat was not.</p></div>`;
  } else if (f.kind === 'pre') {
    body.innerHTML = `<pre>${esc(f.body)}</pre>`;
  } else {
    body.innerHTML = docHtml(f.body);
  }
  $('fileview').hidden = false;
  body.scrollTop = 0;
}

// Tiny markdown-ish renderer: headings, bold, bullets, numbered items, and highlighted author TODOs.
function docHtml(src) {
  const inline = (s) => esc(s)
    .replace(/\*\*(.+?)\*\*/g, '<b>$1</b>')
    .replace(/(\[(?:INSERT|TODO|ref|CHECK)[^\]]*\])/g, '<span class="fv-todo">$1</span>');
  const out = [];
  let list = false;
  for (const line of src.split('\n')) {
    if (/^- /.test(line)) { if (!list) { out.push('<ul>'); list = true; } out.push(`<li>${inline(line.slice(2)) || '&nbsp;'}</li>`); continue; }
    if (list) { out.push('</ul>'); list = false; }
    if (/^# /.test(line)) out.push(`<h1>${inline(line.slice(2))}</h1>`);
    else if (/^## /.test(line)) out.push(`<h2>${inline(line.slice(3))}</h2>`);
    else if (line.trim()) out.push(`<p>${inline(line)}</p>`);
  }
  if (list) out.push('</ul>');
  return out.join('');
}
